const data = [
  {
    score: "83",
    place: "LW",
    flag: "./IMAGE/tunisie.png",
    team: "./IMAGE/AL-ARABI.png",
    playerimg: "./IMAGE/MSAKNI.jpeg",
    name: "YOUSSEF MSAKNI",
    pac: 84,
    sho: 82,
    pas: 78,
    dri: 84,
    def: 40,
    phy: 36,
  },
  {
    score: "71",
    place: "RW",
    flag: "./IMAGE/tunisie.png",
    team: "./IMAGE/nice.png",
    playerimg: "./IMAGE/abdi.png",
    name: "ALI ABDI",
    pac: 89,
    sho: 60,
    pas: 66,
    dri: 71,
    def: 62,
    phy: 76,
  },
  {
    score: "89",
    place: "LB",
    flag: "./IMAGE/tunisie.png",
    team: "./IMAGE/AL-ahli.png",
    playerimg: "./IMAGE/ALI.png",
    name: "MAALOUL",
    pac: 81,
    sho: 73,
    pas: 75,
    dri: 78,
    def: 71,
    phy: 70,
  },
  {
    score: "88",
    place: "CBB",
    flag: "./IMAGE/tunisie.png",
    team: "./IMAGE/lorient.png",
    playerimg: "./IMAGE/talbi.png",
    name: "MONTASSAR",
    pac: 68,
    sho: 38,
    pas: 49,
    dri: 62,
    def: 76,
    phy: 80,
  },
  {
    score: "89",
    place: "CM",
    flag: "./IMAGE/tunisie.png",
    team: "./IMAGE/ahli-libi.png",
    playerimg: "./IMAGE/chaaleli.png",
    name: "CHAALENI",
    pac: 75,
    sho: 77,
    pas: 77,
    dri: 82,
    def: 48,
    phy: 69,
  },
  {
    score: "91",
    place: "CM",
    flag: "./IMAGE/tunisie.png",
    team: "./IMAGE/ferencvarosi.png",
    playerimg:  "./IMAGE/ben-romdhane.png",
    name: "MOAMED ALI",
    pac: 72,
    sho: 72,
    pas: 72,
    dri: 72,
    def: 68,
    phy: 77,
  },
];

export default data;
